### ISSUE TITLE
PEER TO PEER CODE REVIEW

### ISSUE THREAD

**Issue by aneallaryea100** [danigalindo10/tv-shows#24]
Hello @Eternalgratis and @danigalindo10 !

Great work so far 👍 😃 🤭 
REQUIRED CHANGES ♻️ ♻️ ♻️ 

- [x] Kindly apply HTML semantics for easy readability.
- [x] Kindly work on your submit buttons.

**Comment by danigalindo10** [comment]
Hello @aneallaryea100,
Thank you for your feedback, I'm going to apply all your suggestions and good practices for my future projects. Have a nice weekend. Happy coding!! 🎊 🎊 🎊
